Other/urls.py
from django.conf.urls import url
from .views import contactUs, sponsor, team, schedule, proshow, app_privacy_policy
from .utils import some_streaming_csv_view

app_name = "Other"

urlpatterns = [
	url(r'^contactus/$', contactUs, name='contactus'),
	url(r'^sponsors/$', sponsor, name='sponsors'),
	url(r'^proshows/$', proshow, name='proshows'),
	url(r'^team/$', team, name='team'),
	url(r'^schedule/$', schedule, name='schedule'),
	url(r'^privacy/$', app_privacy_policy, name='app_privacy_policy'),
	url(r'^csv_download/$', some_streaming_csv_view, name='csv_download'),
	]

UserAuth/urls.py
from django.conf.urls import url
from .views import UserRegistrationView, UserLoginView, activate_account, logout_view, home, Profile, ForgotPasswordView, resetPassword

app_name = "UserAuth"

urlpatterns = [
	url(r'^$', home, name='home'),
	url(r'^signup/$', UserRegistrationView.as_view(), name='user_registration'),
	url(r'^logout/$', logout_view, name='logout'),
	url(r'^signin/$', UserLoginView.as_view(), name='user_login'),
	url(r'^profile/$', Profile, name='profile'),
	url(r'^forgot_password/$', ForgotPasswordView.as_view(), name='forgot_password'),
	url(r'^reset_password/(?P<url>[0-9a-zA-z]+)/$', resetPassword, name='reset_password'),
	url(r'^activate_account/(?P<url>[0-9a-zA-z]+)/$', activate_account, name='activate_account'),
	]

abhisarga2k19/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserAuth.urls')),
    path(r'event/', include('Event.urls')),
    path(r'api/', include('api.urls')),
    path(r'accomodation/', include('Accomodation.urls')),
    path(r'other/', include('Other.urls')),
    # url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^api-token-auth/', obtain_jwt_token),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url
from .views import UserView,ScheduleView, MarkPresenceView, EventView, CheckRegistrationView, RegisterForTeamEventView, RegisterForSingleEventView, MessageFromTeamView,EventCategoryView, SaveDeviceTokenView

app_name = 'api'

urlpatterns = [
	url(r'^user/$', UserView.as_view(), name='user'),
	url(r'^event-categories/$', EventCategoryView.as_view(), name='EventCategoryView'),

	url(r'^events/$', EventView.as_view(), name='events'),
	url(r'^check-registration/$', CheckRegistrationView.as_view(), name='CheckRegistration'),
	url(r'^register-for-team-event/$', RegisterForTeamEventView.as_view(), name='RegisterForTeamEventView'),
	url(r'^register-for-single-event/$', RegisterForSingleEventView.as_view(), name='RegisterForSingleEventView'),
	url(r'^message-from-team/$', MessageFromTeamView.as_view(), name='MessageFromTeamView'),
	url(r'^device-token/$', SaveDeviceTokenView.as_view(), name='SaveDeviceTokenView'),
	url(r'^mark-presence/$', MarkPresenceView.as_view(), name='MarkPresenceView'),
	url(r'^schedule/$', ScheduleView.as_view(), name='ScheduleView'),

	]

Other/models.py
from django.db import models

# Create your models here.

def get_avatar_path(instance, filename):
	return "Volunteer/{0}/{1}".format(instance.name, filename)

def get_sponsor_path(instance, filename):
	return "Sponsor/{0}/{1}".format(instance.name, filename)

class TeamCategory(models.Model):
	name = models.CharField(max_length=200, null=True, blank=True)
	web_priority = models.IntegerField(default=0)
	app_priority = models.IntegerField(default=0)

	def __str__(self):
		return self.name


class Volunteer(models.Model):
	category = models.ForeignKey(TeamCategory, on_delete=models.CASCADE, related_name="team")
	name = models.CharField(max_length=200, null=True, blank=True)
	avatar = models.ImageField(upload_to=get_avatar_path, null=True, blank=True)
	description = models.TextField()
	designation = models.CharField(max_length=200, null=True, blank=True)
	mobile_no = models.CharField(max_length=100, null=True, blank=True)
	email = models.CharField(max_length=100, null=True, blank=True)
	facebook_link = models.CharField(max_length=200, null=True, blank=True)
	instagram_link = models.CharField(max_length=200, null=True, blank=True)
	linkedin_link = models.CharField(max_length=200, null=True, blank=True)
	web_priority = models.IntegerField(default=0)
	app_priority = models.IntegerField(default=0)

	def __str__(self):
		return self.name


class SponsorCategory(models.Model):
	name = models.CharField(max_length=200, null=True, blank=True)
	web_priority = models.IntegerField(default=0)
	app_priority = models.IntegerField(default=0)

	def __str__(self):
		return self.name

class Sponsor(models.Model):
	category = models.ForeignKey(SponsorCategory, on_delete=models.CASCADE, related_name="sponsor_names")
	name = models.CharField(max_length=100, null=True, blank=True)
	website = models.CharField(max_length=100, null=True, blank=True)
	logo = models.ImageField(upload_to=get_sponsor_path, null=True, blank=True)
	web_priority = models.IntegerField(default=0)
	app_priority = models.IntegerField(default=0)

	def __str__(self):
		return self.name

Other/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse

from .models import TeamCategory, Volunteer, Sponsor, SponsorCategory
# Create your views here.

def contactUs(request):
	if request.method == 'GET':
		contact_page = 'Other/contact_page.html' 
		return render(request, contact_page)

def sponsor(request):
	if request.method == 'GET':
		category = SponsorCategory.objects.all().order_by("web_priority")
		all_sponsors = list()
		for cat in category:
			sponsors = Sponsor.objects.filter(category__id=cat.id).order_by("web_priority")
			all_sponsors.append({"category":cat, "sponsors":sponsors})
		return render(request, 'Other/sponsor.html', {"all_sponsors":all_sponsors})

def proshow(request):
	if request.method == 'GET':
		return render(request, 'Other/proshow.html')

def team(request):
	if request.method == 'GET':
		category = TeamCategory.objects.all().order_by("web_priority")
		all_volunteer = list()
		for cat in category:
			volunteers = Volunteer.objects.filter(category__id=cat.id).order_by("web_priority")
			all_volunteer.append({"category":cat, "volunteers":volunteers})
		return render(request, 'Other/team.html', {"objects":all_volunteer})

def schedule(request):
	if request.method == 'GET':
		return render(request, 'Other/schedule.html')

def app_privacy_policy(request):
	if request.method == 'GET':
		return render(request, 'Other/privacy.html')

Other/templates/Other/contact_page.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}

{% block page-title %}
  <title>Contact Us | Abhisarga 2k19</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/contact.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
<script src="{% static 'assets/js/accomodation.js' %}"></script>
<script src="{% static 'assets/js/menu.js' %}"></script>
{% endblock %}

{% block content %}
<div id="bar">
  <a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
  <div id="menu" onclick="menuopen()">
    <div></div>
    <div></div>
    <div></div>
  </div>
  {% if request.user.is_authenticated %}
  <div id="login">
    <a href="{% url 'UserAuth:logout' %}">Log Out</a>
  </div>
  <div id="register">
    <a href="{% url 'UserAuth:profile' %}">Profile</a>
  </div>
  {% else %}
  <div id="register">
    <a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
  </div>
  <div id="login">
    <a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
  </div>
  {% endif %}
</div>
<div id="full">
  <div id="contact-head">
    <h1>Contact Us</h1>
    <p>
      For any queries please contact
      <br>
      <br>
      Prathyush Potluri
      <br>
      <a href="tel:8187808108"><img src="{% static 'assets/img/svg/phone.svg' %}" alt="">8187808108</a>
      <br>
      <a href="mailto:prathyush.p16@iiits.in"><img src="{% static 'assets/img/svg/email.svg' %}" alt="">prathyush.p16@iiits.in</a>
      <br>
      <br>
      Sowmya Vasuki
      <br>
      <a href="tel:9440902889"><img src="{% static 'assets/img/svg/phone.svg' %}" alt="">9440902889</a>
      <br>
      <a href="mailto:sowmyavasuki.j16@iiits.in"><img src="{% static 'assets/img/svg/email.svg' %}" alt="">sowmyavasuki.j16@iiits.in</a>
      <br>
      <br>
      Krishna Kumar Dey
      <br>
      <a href="tel:7780744336"><img src="{% static 'assets/img/svg/phone.svg' %}" alt="">7780744336</a>
      <br>
      <a href="mailto:krishnakumar.d16@iiits.in"><img src="{% static 'assets/img/svg/email.svg' %}" alt="">krishnakumar.d16@iiits.in</a>
      <br>
      <br>
      or drop us a mail at <a href="mailto:abhisarga@iiits.in" style="margin: 0; padding: 0;">abhisarga@iiits.in</a>
    </p>
  </div>
  <div id="googlemaps">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3878.653707084532!2d80.02393425035366!3d13.556822305387598!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a4d773f1e0f8721%3A0xadb0842ffc2719e4!2sIndian+Institute+of+Information+Technology+Sri+City!5e0!3m2!1sen!2sin!4v1552065298958" width="100%" height="100%" frameborder="0" style="border: 0"></iframe>
  </div>
</div>
{% endblock %}

Other/templates/Other/csv_download.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
	function loadData(){
		event_id = document.getElementById("select_event").value;
		$("#load_data").html( 'Loading....' ).load( '{% url 'Other:csv_download' %}?event_id=' + event_id );
		console.log(event_id);
	}
</script>
<form action="{% url 'Other:csv_download' %}" method="post">
	{% csrf_token %}
	<label>Select Event</label>
	<select name="id" onchange="loadData()" id="select_event">
		{% for event in events %}
		<option value="{{event.id}}">{{event.name}}</option>
		{% endfor %}
	</select>
	<br>
	<button type="submit">Download</button>
	<div id="load_data">
		
	</div>
</form>

Other/templates/Other/event_data.html
<h3>{{event}}</h3><br>

{% for team in teams %}
	<h4>Team Name : {{team.team_name}}</h4>
	<ul>
		<li>{{team.leader.first_name}} {{team.leader.last_name}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{team.leader.mobile_no}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{team.leader.college_name}}</li>
		{% for member in team.belong_to_team.all %}
		<li>{{member.name}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{member.email}}</li>
		{% endfor %}
	</ul>
	<br><br>
{% endfor %}

Other/templates/Other/privacy.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>App Privacy Policy | ABHISARGA 2K19</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5, minimum-scale=1" />
		<meta name="description" content="Abhisarga 2k19: 29th and 31st March. Abhisarga is the annual cultural fest of the Indian Institute of Information Technology, Sri City. Growing exponentially each year, this year is going to be even more power-packed." />
			<meta name="og:type" content="Website" />
	    <meta name="og:site_name" content="Abhisarga 2K19" />
	    <meta name="og:image" content="abhisarga.iiits.in/logo.png" />
			<meta name="og:url" content="abhisarga.iiits.in" />
			<meta name="og:description" content="Abhisarga 2k19: 29th and 31st March. Abhisarga is the annual cultural fest of the Indian Institute of Information Technology, Sri City. Growing exponentially each year, this year is going to be even more power-packed." />
			<meta name="theme-color" content="#05010b" />
	</head>
	<body>
		<div style="white-space: pre-wrap;">
Privacy Policy

IIIT Sri City built the Abhisarga 2k19 app as a Free app. This SERVICE is provided by IIIT Sri City at no cost and is intended for use as is.

This page is used to inform visitors regarding our policies with the collection, use, and disclosure of Personal Information if anyone decided to use our Service.

If you choose to use our Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that we collect is used for providing and improving the Service. We will not use or share your information with anyone except as described in this Privacy Policy.

The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible at Abhisarga 2k19 unless otherwise defined in this Privacy Policy.

Information Collection and Use

For a better experience, while using our Service, we may require you to provide us with certain personally identifiable information, including but not limited to Camera used to scan QR code.. The information that we request will be retained by us and used as described in this privacy policy.

The app does use third party services that may collect information used to identify you.

Link to privacy policy of third party service providers used by the app

Google Play Services
Log Data

We want to inform you that whenever you use our Service, in a case of an error in the app we collect data and information (through third party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing our Service, the time and date of your use of the Service, and other statistics.

Cookies

Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.

This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service.

Service Providers

We may employ third-party companies and individuals due to the following reasons:

To facilitate our Service;
To provide the Service on our behalf;
To perform Service-related services; or
To assist us in analyzing how our Service is used.
We want to inform users of this Service that these third parties have access to your Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they are obligated not to disclose or use the information for any other purpose.

Security

We value your trust in providing us your Personal Information, thus we are striving to use commercially acceptable means of protecting it. But remember that no method of transmission over the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee its absolute security.

Links to Other Sites

This Service may contain links to other sites. If you click on a third-party link, you will be directed to that site. Note that these external sites are not operated by us. Therefore, we strongly advise you to review the Privacy Policy of these websites. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.

Children’s Privacy

These Services do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13. In the case we discover that a child under 13 has provided us with personal information, we immediately delete this from our servers. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we will be able to do necessary actions.

Changes to This Privacy Policy

We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes. We will notify you of any changes by posting the new Privacy Policy on this page. These changes are effective immediately after they are posted on this page.

Contact Us

If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us.

This privacy policy page was created at privacypolicytemplate.net and modified/generated by App Privacy Policy Generator
		</div>
	</body>
</html>

Other/templates/Other/proshow.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}

{% block page-title %}
	<title>Proshows | Abhisarga 2k19</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/proshow.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
<script src="{% static 'assets/js/menu.js' %}"></script>
{% endblock %}

{% block content %}
<div id="bar">
  <a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
  <div id="menu" onclick="menuopen()">
    <div></div>
    <div></div>
    <div></div>
  </div>
	{% if request.user.is_authenticated %}
	<div id="login">
		<a href="{% url 'UserAuth:logout' %}">Log Out</a>
	</div>
	<div id="register">
		<a href="{% url 'UserAuth:profile' %}">Profile</a>
	</div>
	{% else %}
	<div id="register">
		<a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
	</div>
	<div id="login">
		<a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
	</div>
	{% endif %}
</div>
<div id="proposter">
    <img src="{% static 'assets/img/proshow.png' %}" alt="Prowshow">
</div>
{% endblock %}

Other/templates/Other/schedule.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}

{% block page-title %}
	<title>Schedule | Abhisarga 2k19</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/proshow.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
<script src="{% static 'assets/js/menu.js' %}"></script>
{% endblock %}

{% block content %}
<div id="bar">
  <a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
  <div id="menu" onclick="menuopen()">
    <div></div>
    <div></div>
    <div></div>
  </div>
	{% if request.user.is_authenticated %}
	<div id="login">
		<a href="{% url 'UserAuth:logout' %}">Log Out</a>
	</div>
	<div id="register">
		<a href="{% url 'UserAuth:profile' %}">Profile</a>
	</div>
	{% else %}
	<div id="register">
		<a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
	</div>
	<div id="login">
		<a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
	</div>
	{% endif %}
</div>
<div id="proposter">
    <img src="{% static 'assets/img/Events_schedule.png' %}" alt="Events Schedule">
</div>
{% endblock %}

Other/templates/Other/sponsor.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}

{% block page-title %}
	<title>Sponsors | Abhisarga 2k19</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/sponsor.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
<script src="{% static 'assets/js/menu.js' %}"></script>
{% endblock %}

{% block content %}
<div id="bar">
  <a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
  <div id="menu" onclick="menuopen()">
    <div></div>
    <div></div>
    <div></div>
  </div>
	{% if request.user.is_authenticated %}
	<div id="login">
		<a href="{% url 'UserAuth:logout' %}">Log Out</a>
	</div>
	<div id="register">
		<a href="{% url 'UserAuth:profile' %}">Profile</a>
	</div>
	{% else %}
	<div id="register">
		<a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
	</div>
	<div id="login">
		<a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
	</div>
	{% endif %}
</div>
{% for obj in all_sponsors %}
<div class="sponsorcategory">
	<h1>{{ obj.category.name }}</h1>
	{% for sponsor in obj.sponsors %}
	<div class="sponsorblock">
	  <h1>{{ sponsor.name }}</h1>
	  <div>
	    <a href="{{ sponsor.website }}"><img src="{{ sponsor.logo.url }}"></a>
	  </div>
	</div>
	{% endfor %}
</div>
{% endfor %}

{% endblock %}

Other/templates/Other/team.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}
{% block page-title %}
<title>Our Team | ABHISARGA 2K19</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/usercard.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/team.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
<script src="{% static 'assets/js/menu.js' %}"></script>
{% endblock %}
{% block content %}
<div id="bar">
  <a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
  <div id="menu" onclick="menuopen()">
    <div></div>
    <div></div>
    <div></div>
  </div>
  {% if request.user.is_authenticated %}
  <div id="login">
    <a href="{% url 'UserAuth:logout' %}">Log Out</a>
  </div>
  <div id="register">
    <a href="{% url 'UserAuth:profile' %}">Profile</a>
  </div>
  {% else %}
  <div id="register">
    <a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
  </div>
  <div id="login">
    <a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
  </div>
  {% endif %}
</div>
<div class="contact-head">
  <h1>Our Team</h1>
</div>
{% for object in objects %}
<div class="contact-department">
  <h1>{{ object.category.name }}</h1>
  <div class="contact-cards">
    {% for volunteer in object.volunteers %}
    <div class="user-card">
      <div class="user-details">
        <h1>{{ volunteer.name }}</h1>
        <p>
          {{ volunteer.description }}
        </p>
      </div>
      <div class="user-full">
        <div class="user-image">
          {% if volunteer.avatar %}
          <img src="{{ volunteer.avatar.url }}" alt="{{ volunteer.name }}">
          {% endif %}
        </div>
        <div class="user-hidden">
          <h1>{{ volunteer.name }}</h1>
          <h2>{{ volunteer.designation }}</h2>
          <div class="user-contact">
            <div class="user-phone"><a href="#">{{ volunteer.mobile_no }}</a></div>
            <div class="user-email"><a href="mailto:{{ volunteer.email }}">{{ volunteer.email }}</a></div>
            <div class="user-social">
              <a href="{% if volunteer.facebook_link %}{{ volunteer.facebook_link }}{% endif %}"><img src="{% static 'assets/img/fb.png' %}" alt=""></a>
              <a href="{% if volunteer.instagram_link %}{{ volunteer.instagram_link }}{% endif %}"><img src="{% static 'assets/img/insta.png' %}" alt=""></a>
              <a href="{% if volunteer.linkedin_link %}{{ volunteer.linkedin_link }}{% endif %}"><img src="{% static 'assets/img/linkedin.png' %}" alt=""></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endfor %}
{% endblock %}