Accomodation/urls.py
from django.conf.urls import url
from .views import Accomodation

app_name = "Accomodation"

urlpatterns = [
	url(r'^$', Accomodation, name='accomodation'),
	]

Event/urls.py
from django.conf.urls import url
from .views import event, eventRegistration, teamEventRegistration, eventTeamEdit

app_name = "Event"

urlpatterns = [
	url(r'^$', event, name='events'),
	url(r'^eventRegistration/$', eventRegistration, name='eventRegistration'),
	url(r'^teamEventRegistration/$', teamEventRegistration, name='teamEventRegistration'),
	url(r'^eventTeamEdit/$', eventTeamEdit, name='eventTeamEdit'),
	]

Other/urls.py
from django.conf.urls import url
from .views import contactUs, sponsor, team, schedule, proshow, app_privacy_policy
from .utils import some_streaming_csv_view

app_name = "Other"

urlpatterns = [
	url(r'^contactus/$', contactUs, name='contactus'),
	url(r'^sponsors/$', sponsor, name='sponsors'),
	url(r'^proshows/$', proshow, name='proshows'),
	url(r'^team/$', team, name='team'),
	url(r'^schedule/$', schedule, name='schedule'),
	url(r'^privacy/$', app_privacy_policy, name='app_privacy_policy'),
	url(r'^csv_download/$', some_streaming_csv_view, name='csv_download'),
	]

UserAuth/urls.py
from django.conf.urls import url
from .views import UserRegistrationView, UserLoginView, activate_account, logout_view, home, Profile, ForgotPasswordView, resetPassword

app_name = "UserAuth"

urlpatterns = [
	url(r'^$', home, name='home'),
	url(r'^signup/$', UserRegistrationView.as_view(), name='user_registration'),
	url(r'^logout/$', logout_view, name='logout'),
	url(r'^signin/$', UserLoginView.as_view(), name='user_login'),
	url(r'^profile/$', Profile, name='profile'),
	url(r'^forgot_password/$', ForgotPasswordView.as_view(), name='forgot_password'),
	url(r'^reset_password/(?P<url>[0-9a-zA-z]+)/$', resetPassword, name='reset_password'),
	url(r'^activate_account/(?P<url>[0-9a-zA-z]+)/$', activate_account, name='activate_account'),
	]

abhisarga2k19/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserAuth.urls')),
    path(r'event/', include('Event.urls')),
    path(r'api/', include('api.urls')),
    path(r'accomodation/', include('Accomodation.urls')),
    path(r'other/', include('Other.urls')),
    # url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^api-token-auth/', obtain_jwt_token),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url
from .views import UserView,ScheduleView, MarkPresenceView, EventView, CheckRegistrationView, RegisterForTeamEventView, RegisterForSingleEventView, MessageFromTeamView,EventCategoryView, SaveDeviceTokenView

app_name = 'api'

urlpatterns = [
	url(r'^user/$', UserView.as_view(), name='user'),
	url(r'^event-categories/$', EventCategoryView.as_view(), name='EventCategoryView'),

	url(r'^events/$', EventView.as_view(), name='events'),
	url(r'^check-registration/$', CheckRegistrationView.as_view(), name='CheckRegistration'),
	url(r'^register-for-team-event/$', RegisterForTeamEventView.as_view(), name='RegisterForTeamEventView'),
	url(r'^register-for-single-event/$', RegisterForSingleEventView.as_view(), name='RegisterForSingleEventView'),
	url(r'^message-from-team/$', MessageFromTeamView.as_view(), name='MessageFromTeamView'),
	url(r'^device-token/$', SaveDeviceTokenView.as_view(), name='SaveDeviceTokenView'),
	url(r'^mark-presence/$', MarkPresenceView.as_view(), name='MarkPresenceView'),
	url(r'^schedule/$', ScheduleView.as_view(), name='ScheduleView'),

	]

UserAuth/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

# Create your models here.

def get_image_upload_path(instance, filename):
	return "Profile/{0}/{1}".format(instance.username, filename)

class User(AbstractUser):
	mobile_no = models.CharField(max_length=15, null=True, blank=True)
	college_name = models.CharField(max_length=100, null=True, blank=True)
	description = models.CharField(max_length=150, null=True, blank=True)
	profile_pic = models.ImageField(upload_to=get_image_upload_path, null=True, blank=True)

	activation_link = models.CharField(max_length=200, null=True, blank=True)
	is_verified = models.BooleanField(default=False)

	device_token = models.CharField(max_length=200, null=True, blank=True)

	def __str__(self):
		return str(self.username)	

UserAuth/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils.crypto import get_random_string
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.template.loader import render_to_string
import threading

from .models import User
from Event.models import Event, EventCategory, Team, Member
from api.models import MessageToParticipant
# Create your views here.

def home(request):
	home_page = 'UserAuth/main.html'
	event_cat = EventCategory.objects.all().order_by("web_priority")
	events = Event.objects.all().order_by("web_priority")
	messages = MessageToParticipant.objects.all().order_by("-id")[:3]
	# print(messages)
	return render(request, home_page, {"event_category":event_cat, "events":events, "messages":messages})

class UserRegistrationView(View):
	signup_template = 'UserAuth/register.html'
	account_confirmation_page = 'UserAuth/account_confirmation_page.html'

	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			return HttpResponseRedirect(reverse('Event:events'))
		return render(request, self.signup_template)
		
	def post(self, request, *args, **kwargs):
		first_name = request.POST.get('first_name')
		last_name = request.POST.get('last_name')
		email = request.POST.get('email')
		mobile_no = request.POST.get('mobile_no')
		college_name = request.POST.get('college_name')
		description = request.POST.get('description')
		password = request.POST.get('password')

		if password:
			try:
				user = User()
				user.username = email.split('@')[0]
				user.first_name = first_name
				user.last_name = last_name
				user.email = email
				user.mobile_no = mobile_no
				user.college_name = college_name
				user.description = description
				user.set_password(password)
				user.save()

				send_account_activation_url(request, user.username)
				return render(request, self.account_confirmation_page)
			except Exception as e:
				print(e)
				return render(request, self.signup_template, {"message":"User is already registered."})
		return render(request, self.signup_template, {"message":"Something went wrong."})


class UserLoginView(View):
	signin_template = 'UserAuth/login.html'
	account_confirmation_page = 'UserAuth/account_confirmation_page.html'
	homepage = 'Event/events.html'

	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			return HttpResponseRedirect(reverse('Event:events'))
		return render(request, self.signin_template)

	def post(self, request, *args, **kwargs):
		email = request.POST.get('email')
		password = request.POST.get('password')
		try:
			user = User.objects.get(username=email.split('@')[0])
		except:
			return render(request, self.signin_template, {"message":"Wrong email or password."})
		if user.is_verified:
			user = authenticate(username=user.username, password=password)
			if user is not None:
				login(request, user)
				if request.GET.get('next'):
					return redirect(request.GET.get('next'))
				return HttpResponseRedirect(reverse('Event:events'))
			return render(request, self.signin_template, {"message":"Wrong email or password."})
		else:
			send_account_activation_url(request, user.username)
			return render(request, self.account_confirmation_page, {"message": "Account is not activated. Please activate your account."})

def send_email(subject, to_email, text_content, html_content):
	from django.core.mail import EmailMultiAlternatives
	# print(subject, to_email, text_content, html_content)
	subject, from_email, to = subject, settings.EMAIL_HOST_USER , to_email
	text_content = text_content
	html_content = html_content
	msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
	msg.attach_alternative(html_content, "text/html")
	print(msg)
	msg.send()
	return

def send_account_activation_url(request, username):
	account_confirmation_page = 'UserAuth/account_confirmation_page.html'
	user = get_object_or_404(User, username=username)
	url = get_random_string(150)
	absolute_url = request.build_absolute_uri(url)
	activation_url = absolute_url.replace("signin", "activate_account")
	activation_url = activation_url.replace("signup", "activate_account")
	print(activation_url)
	user.activation_link = url
	user.save()
	try:
		thread_process = threading.Thread(target=send_email, kwargs={
			"subject":"Abhisarga Account Activation",
			"to_email":user.email,
			"text_content":"",
			"html_content": render_to_string('UserAuth/email_activation_template.html', {"user_fullname":str(user.first_name)+" "+str(user.last_name), "link":activation_url})
			})
		thread_process.start()
	except Exception as e:
		print(e)
	return
	# return render(request, account_confirmation_page)

@login_required(login_url=settings.LOGIN_REDIRECT_URL)
def logout_view(request):
	logout(request)
	return redirect('/')

@login_required(login_url=settings.LOGIN_REDIRECT_URL)
def Profile(request):
	profile_page = 'UserAuth/profile.html'
	if request.method=='GET':
		try:
			participated_events = Team.objects.filter(leader__username=request.user.username)
			part = list()
			for obj in participated_events:
				part.append({"event":obj.event, "team":{"leader": obj,"members": obj.belong_to_team.all()}})

			participated_events = Member.objects.filter(email=request.user.email)
			for obj in participated_events:
				part.append({"event":obj.team.event, "team":{"leader": obj.team,"members": obj.team.belong_to_team.all()}})
		except Exception as e:
			pass
			# print(obj)
		return render(request, profile_page, {"participated_events":part})

def activate_account(request, url):
	try:
		user = User.objects.get(activation_link=url)
		user.activation_link = ""
		user.is_verified = True
		user.save()
		return HttpResponseRedirect(reverse('UserAuth:user_login'))
	except Exception as e:
		return HttpResponseRedirect(reverse('UserAuth:user_login'))


class ForgotPasswordView(View):
	template = "UserAuth/forgot_password.html"

	def get(self, request, *args, **kwargs):
		return render(request, self.template)

	def post(self, request, *args, **kwargs):
		email = request.POST.get('email')
		try:
			user = User.objects.get(email=email)
			url = get_random_string(150)
			absolute_url = request.build_absolute_uri(url)
			activation_url = absolute_url.replace("forgot_password", "reset_password")
			user.activation_link = url
			user.save()
			try:
				thread_process = threading.Thread(target=send_email, kwargs={
					"subject":"Abhisarga Account Password Reset",
					"to_email":user.email,
					"text_content":"",
					"html_content": render_to_string('UserAuth/forgot_password_template.html', {"user_fullname":str(user.first_name)+" "+str(user.last_name), "link":activation_url})
					})
				thread_process.start()
			except Exception as e:
				print(e)
			return render(request, self.template, {"message":"Password reset link is sent to your email. Please check your email."})
		except Exception as e:
			print(e)
			return render(request, self.template, {"message":"Wrong email address."})


def resetPassword(request, url):
	if request.method == 'GET':
		return render(request, "UserAuth/reset_password.html", {"url":url})

	if request.method == 'POST':
		reset_link = url
		password = request.POST.get('password')
		try:
			user = User.objects.get(activation_link=reset_link)
			# print(user)
			if password:
				user.set_password(password)
				user.activation_url=""
				user.save()
			return HttpResponseRedirect(reverse('UserAuth:user_login'))
		except Exception as e:
			print(e)
			return render(request, "UserAuth/forgot_password.html", {"message":"Password reset link expired. Please try again."})

UserAuth/templates/UserAuth/forgot_password.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}

{% block page-title %}
	<title>Forgot Password | Abhisarga 2k19</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/login.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
<script src="{% static 'assets/js/menu.js' %}"></script>
{% endblock %}

{% block content %}
<div id="bar">
  <a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
  <div id="menu" onclick="menuopen()">
    <div></div>
    <div></div>
    <div></div>
  </div>
	{% if request.user.is_authenticated %}
	<div id="login">
		<a href="{% url 'UserAuth:logout' %}">Log Out</a>
	</div>
	<div id="register">
		<a href="javascript:function()">Profile</a>
	</div>
	{% else %}
	<div id="register">
		<a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
	</div>
	<div id="login">
		<a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
	</div>
	{% endif %}
</div>
<div id="accomodation">
  <div id="accomodation-content">
    <h1>Forgot Password</h1>
    <div id="formholder">
    	<div id="formdiv">
		    <form accept="{% url 'UserAuth:forgot_password' %}" method="post">
		    	<div>
			    	<label for="email"><img src="{% static 'assets/img/svg/email.svg' %}" alt=""></label><input type="email" placeholder="E-mail" name="email" required="">
			    </div>
		    </form>
		</div>
	</div>
    
    <p>
    	Activation link is sent to your email. Please check your email.
    </p>
   </div>
</div>
{% endblock %}

UserAuth/templates/UserAuth/home_page.html
<a href="{% url 'UserAuth:user_login' %}">Login</a><br><br>
<a href="{% url 'UserAuth:user_registration' %}">Register</a>

UserAuth/templates/UserAuth/homepage.html
<h1>Abhisarga 2k19</h1>
<a href="{% url 'UserAuth:logout' %}">logout</a>

UserAuth/templates/UserAuth/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		{% block page-title %}
		
		{% endblock %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5, minimum-scale=1" />
		<meta name="description" content="Abhisarga 2k19: 29th and 31st March. Abhisarga is the annual cultural fest of the Indian Institute of Information Technology, Sri City. Growing exponentially each year, this year is going to be even more power-packed." />
		<meta name="og:type" content="Website" />
    <meta name="og:site_name" content="Abhisarga 2K19" />
    <meta name="og:image" content="abhisarga.iiits.in/logo.png" />
		<meta name="og:url" content="abhisarga.iiits.in" />
		<meta name="og:description" content="Abhisarga 2k19: 29th and 31st March. Abhisarga is the annual cultural fest of the Indian Institute of Information Technology, Sri City. Growing exponentially each year, this year is going to be even more power-packed." />
		<meta name="theme-color" content="#05010b" />
	{% block link %}
    	
	{% endblock %}
  </head>
  <body onload="initialize()">
    {% block content %}
    {% endblock %}
    <div id="footer">
			<div id="links">
				<div>
					Links
					<hr align="left" width="20%">
				</div>
				<ul>
					<li><a href="{% url 'Accomodation:accomodation' %}">Accommodation</a></li>
					<li><a href="{% url 'Other:team' %}">Team</a></li>
					<li><a href="{% url 'Other:contactus' %}">Contact Us</a></li>
				</ul>
			</div>
			<div id="title">
				<div>
					Abhisarga'19
					<hr align="left" width="40%">
				</div>
				<ul>
					<li><a href="{% url 'Event:events' %}">Events</a></li>
					<li><a href="{% url 'Other:sponsors' %}">Sponsors</a></li>
					<li><a href="{% url 'Other:schedule' %}">Schedule</a></li>
				</ul>
			</div>
			<div id="social">
				<div>
					Follow Us
					<hr align="left" width="40%">
				</div>
				<br>
				<a href="https://www.facebook.com/abhisarga/"><img src="{% static 'assets/img/fb.png' %}" alt="Facebook"></a>
				<a href="https://www.instagram.com/abhisarga/"><img src="{% static 'assets/img/insta.png' %}" alt="Instagram"></a>
				<a href="https://www.youtube.com/channel/UCf1DbeeTKGzpwRv9X7YECfg"><img src="{% static 'assets/img/youtube.png' %}" alt="Youtube"></a>
				<br>
				<a href="https://play.google.com/store/apps/details?id=com.abhisarga.mobileapp" target="_blank"><img src="{% static 'assets/img/googleplay.png' %}" alt="Google Play Store" style="width: 5em; height: 2.2em"></a>
			</div>
			<div id="copyright">Copyright 2019 - All rights reserved</div>
    </div>
    {% block popup %}
	{% endblock %}
		<div id="fullmenu">
			<div id="close" onclick="menuclose()">
				<hr id="close1">
				<hr id="close2">
			</div>
			<div id="inlogo">
				<img src="{% static 'assets/img/logo-min.png' %}" alt="Abhisarga Logo">
				<div id="icons-flex">
					<a href="https://www.facebook.com/abhisarga/"><img src="{% static 'assets/img/fb.png' %}" alt="Facebook" class="icons"></a>
					<a href="https://www.instagram.com/abhisarga/"><img src="{% static 'assets/img/insta.png' %}" alt="Instagram" class="icons"></a>
					<a href="https://www.youtube.com/channel/UCf1DbeeTKGzpwRv9X7YECfg"><img src="{% static 'assets/img/youtube.png' %}" alt="Youtube" class="icons"></a>
				</div>
			</div>
			<div id="list">
				<ul>
					<li><a href="{% url 'UserAuth:home' %}">Home</a><hr></li>
					<li><a href="{% url 'Event:events' %}">Events</a><hr></li>
					<li><a href="{% url 'Other:proshows' %}">Proshows</a><hr></li>
					<li><a href="{% url 'Accomodation:accomodation' %}">Accommodation</a><hr></li>
					<li><a href="{% url 'Other:sponsors' %}">Sponsors</a><hr></li>
					<li><a href="{% url 'Other:team' %}">Team</a><hr></li>
					<li><a href="{% url 'Other:contactus' %}">Contact Us</a><hr></li>
				</ul>
			</div>
		</div>
  </body>
</html>

UserAuth/templates/UserAuth/login.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}

{% block page-title %}
	<title>Login | Abhisarga 2k19</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/login.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
<script src="{% static 'assets/js/menu.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="bar">
      <a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
      <div id="menu" onclick="menuopen()">
        <div></div>
        <div></div>
        <div></div>
      </div>
      <div id="register">
        <!-- <img src="{% static 'assets/img/svg/circdsg1.svg' %}" width="80%" height="20%" alt=""> -->
        <a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
        <!-- <img src="{% static 'assets/img/svg/circdsg2.svg' %}" width="80%" height="20%" alt=""> -->
      </div>
      <div id="login">
        <!-- <img src="{% static 'assets/img/svg/circdsg1.svg' %}" width="80%" height="20%" alt=""> -->
        <a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
        <!-- <img src="{% static 'assets/img/svg/circdsg2.svg' %}" width="80%" height="20%" alt=""> -->
      </div>
    </div>
		<div id="formholder">
			<img class="obj" id="triangle" src="{% static 'assets/img/svg/triangle.svg' %}" alt="">
      <img class="obj" id="circle" src="{% static 'assets/img/svg/circle.svg' %}" alt="">
      <img class="obj" id="rhombus" src="{% static 'assets/img/svg/rhombus.svg' %}" alt="">
      <div id="formlogo">
        <img src="{% static 'assets/img/logo-min.png' %}" alt="Abhisarga 2019">
      </div>
      <div id="formdiv">
        {% if message %}{{ message }}{% endif %}
        <form action="{% url 'UserAuth:user_login' %}" method="post">
        	{% csrf_token %}
          <div>
            <label for="email"><img src="{% static 'assets/img/svg/email.svg' %}" alt=""></label><input type="email" placeholder="E-mail" name="email" required="">
          </div>
          <br>
          <div>
            <label for="password"><img src="{% static 'assets/img/svg/password.svg' %}" alt=""></label><input type="password" placeholder="Password" name="password" required="">
          </div>
          <br>
          <div>
            <button type="submit">Login</button>
          </div>
          <br>
          <span>Not Registered Yet? <a href="{% url 'UserAuth:user_registration' %}">Register here</a></span>
          <span><a href="{% url 'UserAuth:forgot_password' %}">Forgot Password?</a></span>
        </form>
      </div>
    </div>
{% endblock %}

UserAuth/templates/UserAuth/profile.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}
{% block page-title %}
<title>Profile | ABHISARGA 2K19</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/profile.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
<script src="{% static 'assets/js/menu.js' %}"></script>
{% endblock %}

{% block content %}
<div id="bar">
	<a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
	<div id="menu" onclick="menuopen()">
		<div></div>
		<div></div>
		<div></div>
	</div>
	{% if request.user.is_authenticated %}
	<div id="login">
		<a href="{% url 'UserAuth:logout' %}">Log Out</a>
	</div>
	<div id="register">
		<a href="{% url 'UserAuth:profile' %}">Profile</a>
	</div>
	{% else %}
	<div id="register">
		<a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
	</div>
	<div id="login">
		<a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
	</div>
	{% endif %}
</div>
<div id="profile-content">
	<div id="account">
	<div id="profile-image">
		{% if request.user.profile_pic %}
	  	<img src="{{ request.user.profile.url }}" alt="">
		{% else %}
		<img src="{% static 'assets/img/default-male.png' %}" alt="">
		{% endif %}
	</div>
	<div id="profile-name">
	  <!-- <img src="{% static 'assets/img/svg/edit.svg' %}" alt=""> -->
	  {% if request.user.first_name %}
	  	{{ request.user.first_name }}
	  {% endif %}
	</div>
	<div id="profile-college">
	  <!-- <img src="{% static 'assets/img/svg/edit.svg' %}" alt=""> -->
	  {% if request.user.college_name %}
	  {{ request.user.college_name }}
	  {% endif %}
	</div>
	</div>
	<div id="reg-events">
	<h1>Enrolled Events</h1>
	<ul>
		{% for object in participated_events %}
		  <li>
		    <div class="single-reg-event">
		      <h1><img src="{% static 'assets/img/svg/check.svg' %}" alt="">{{ object.event.name }}</h1>
		      <img src="{% static 'assets/img/svg/dotline.svg' %}">
		      <span><img src="{% static 'assets/img/svg/calender.svg' %}" alt="">{{ object.event.event_from|date:"M d, Y" }}</span>
		      <span><img src="{% static 'assets/img/svg/rupee.svg' %}" alt="">{{ object.event.prize }}</span>
		      {% if object.event.team_event %}
		      <span><img src="{% static 'assets/img/svg/group.svg' %}" alt="">{{ object.team.leader.team_name }} Members</span>
		      <ul>
		      	<li><img src="{% static 'assets/img/svg/circlebullet.svg' %}" alt="">{{object.team.leader.leader.first_name}}</li>
		      	{% for member in object.team.members %}
		        <li><img src="{% static 'assets/img/svg/circlebullet.svg' %}" alt="">{{member.name}}</li>
		       	{% endfor %}
		       </ul>
		      {% endif %}
		      <button class="deregister" onclick="deregister_event('{{object.event.id}}')">De Register</button>
		    </div>
		  </li>
		  <br>
	  	{% endfor %}
	</ul>
	</div>
</div>
<script type="text/javascript">
	function deregister_event(event_id){
		if(confirm('Are you sure you want to deregister from this event?')){
			window.location.href='{% url 'Event:eventRegistration' %}?event_id='+event_id;
		}
	}
</script>
{% endblock %}

UserAuth/templates/UserAuth/reset_password.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}

{% block page-title %}
	<title>Reset Password | Abhisarga 2k19</title>
{% endblock %}

{% block link %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/login.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
<script src="{% static 'assets/js/menu.js' %}"></script>
{% endblock %}

{% block content %}
<div id="bar">
  <a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
  <div id="menu" onclick="menuopen()">
    <div></div>
    <div></div>
    <div></div>
  </div>
	{% if request.user.is_authenticated %}
	<div id="login">
		<a href="{% url 'UserAuth:logout' %}">Log Out</a>
	</div>
	<div id="register">
		<a href="javascript:function()">Profile</a>
	</div>
	{% else %}
	<div id="register">
		<a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
	</div>
	<div id="login">
		<a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
	</div>
	{% endif %}
</div>
<div id="formholder">
	<img class="obj" id="triangle" src="{% static 'assets/img/svg/triangle.svg' %}" alt="">
	<img class="obj" id="circle" src="{% static 'assets/img/svg/circle.svg' %}" alt="">
	<img class="obj" id="rhombus" src="{% static 'assets/img/svg/rhombus.svg' %}" alt="">
	<div id="formlogo">
		<img src="{% static 'assets/img/logo-min.png' %}" alt="Abhisarga 2019">
	</div>
	<div id="formdiv">
		<form action="{% url 'UserAuth:reset_password' url=url %}" method="post">
			{% csrf_token %}
			<div>
	            <label for="password"><img src="{% static 'assets/img/svg/password.svg' %}" alt=""></label><input type="password" placeholder="Password" name="password" required="">
	        </div>
			<br>
			<div>
				<button type="submit">Change Password</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}