Event/urls.py
from django.conf.urls import url
from .views import event, eventRegistration, teamEventRegistration, eventTeamEdit

app_name = "Event"

urlpatterns = [
	url(r'^$', event, name='events'),
	url(r'^eventRegistration/$', eventRegistration, name='eventRegistration'),
	url(r'^teamEventRegistration/$', teamEventRegistration, name='teamEventRegistration'),
	url(r'^eventTeamEdit/$', eventTeamEdit, name='eventTeamEdit'),
	]

UserAuth/urls.py
from django.conf.urls import url
from .views import UserRegistrationView, UserLoginView, activate_account, logout_view, home, Profile, ForgotPasswordView, resetPassword

app_name = "UserAuth"

urlpatterns = [
	url(r'^$', home, name='home'),
	url(r'^signup/$', UserRegistrationView.as_view(), name='user_registration'),
	url(r'^logout/$', logout_view, name='logout'),
	url(r'^signin/$', UserLoginView.as_view(), name='user_login'),
	url(r'^profile/$', Profile, name='profile'),
	url(r'^forgot_password/$', ForgotPasswordView.as_view(), name='forgot_password'),
	url(r'^reset_password/(?P<url>[0-9a-zA-z]+)/$', resetPassword, name='reset_password'),
	url(r'^activate_account/(?P<url>[0-9a-zA-z]+)/$', activate_account, name='activate_account'),
	]

abhisarga2k19/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('UserAuth.urls')),
    path(r'event/', include('Event.urls')),
    path(r'api/', include('api.urls')),
    path(r'accomodation/', include('Accomodation.urls')),
    path(r'other/', include('Other.urls')),
    # url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^api-token-auth/', obtain_jwt_token),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import url
from .views import UserView,ScheduleView, MarkPresenceView, EventView, CheckRegistrationView, RegisterForTeamEventView, RegisterForSingleEventView, MessageFromTeamView,EventCategoryView, SaveDeviceTokenView

app_name = 'api'

urlpatterns = [
	url(r'^user/$', UserView.as_view(), name='user'),
	url(r'^event-categories/$', EventCategoryView.as_view(), name='EventCategoryView'),

	url(r'^events/$', EventView.as_view(), name='events'),
	url(r'^check-registration/$', CheckRegistrationView.as_view(), name='CheckRegistration'),
	url(r'^register-for-team-event/$', RegisterForTeamEventView.as_view(), name='RegisterForTeamEventView'),
	url(r'^register-for-single-event/$', RegisterForSingleEventView.as_view(), name='RegisterForSingleEventView'),
	url(r'^message-from-team/$', MessageFromTeamView.as_view(), name='MessageFromTeamView'),
	url(r'^device-token/$', SaveDeviceTokenView.as_view(), name='SaveDeviceTokenView'),
	url(r'^mark-presence/$', MarkPresenceView.as_view(), name='MarkPresenceView'),
	url(r'^schedule/$', ScheduleView.as_view(), name='ScheduleView'),

	]

Event/models.py
from django.conf import settings
from django.db import models

# Create your models here.

def get_event_photo_path(instance, filename):
	return "Event/{0}/{1}".format(instance.name, filename)

def get_event_category_photo_path(instance, filename):
	return "EventCategory/{0}/{1}".format(instance.category, filename)

class EventCategory(models.Model):
	category = models.CharField(max_length=100, null=True, blank=True)
	image = models.ImageField(upload_to=get_event_category_photo_path, null=True, blank=True)
	description = models.TextField()
	web_priority = models.IntegerField(default=0)
	app_priority = models.IntegerField(default=0)

	def __str__(self):
		return self.category

class Event(models.Model):
	event_category = models.ForeignKey(EventCategory, on_delete=models.CASCADE, related_name="event_category")
	name = models.CharField(max_length=200, null=True, blank=True)
	logo = models.ImageField(upload_to=get_event_photo_path, null=True, blank=True)
	registration_from = models.DateTimeField(null=True, blank=True)
	registration_to = models.DateTimeField(null=True, blank=True)
	event_from = models.DateTimeField(null=True, blank=True)
	event_to = models.DateTimeField(null=True, blank=True)
	participant_limit = models.IntegerField(default=0)
	participant_count = models.IntegerField(default=0)
	description = models.TextField()
	rules = models.TextField()
	prize = models.TextField()
	brochure = models.FileField(upload_to=get_event_photo_path, null=True, blank=True)
	organisers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="organising_events")
	#volunteers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="volunteering_events")
	web_priority = models.IntegerField(default=0)
	app_priority = models.IntegerField(default=0)
	registration_closed = models.BooleanField(default=False)
	team_event = models.BooleanField(default=False)

	img_1 = models.FileField(upload_to=get_event_photo_path, null=True, blank=True)
	img_2 = models.FileField(upload_to=get_event_photo_path, null=True, blank=True)
	img_3 = models.FileField(upload_to=get_event_photo_path, null=True, blank=True)
	img_4 = models.FileField(upload_to=get_event_photo_path, null=True, blank=True)

	qr_code_string = models.CharField(max_length=100, null=True, blank=True)

	@property
	def registration_full(self):
		teams = Team.objects.filter(event__id=self.id)
		return False if len(teams) < self.participant_limit else True

	def __str__(self):
		teams=list()
		if self.id:
			teams = Team.objects.filter(event__id=self.id)
		return str(self.name) + ' - ' + str(len(teams))


class Team(models.Model):
	team_name = models.CharField(max_length=50, null=True, blank=True)
	event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="participating_events")
	leader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="team_leader_of")
	
	present_for_event = models.BooleanField(default=False)

	def __str__(self):
		return str(self.team_name) + ' - ' + str(self.event.name)


class Member(models.Model):
	team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="belong_to_team")
	name = models.CharField(max_length=100, null=True, blank=True)
	email = models.CharField(max_length=100, null=True, blank=True)
	mobile_no = models.CharField(max_length=20, null=True, blank=True)

	def __str__(self):
		return str(self.name) + ' - ' + str(self.email)


class EventCatalogue(models.Model):
	event = models.OneToOneField(Event, on_delete=models.CASCADE, related_name="catalogue_of")
	image1 = models.ImageField(upload_to=get_event_photo_path, null=True, blank=True)
	image2 = models.ImageField(upload_to=get_event_photo_path, null=True, blank=True)
	image3 = models.ImageField(upload_to=get_event_photo_path, null=True, blank=True)
	image4 = models.ImageField(upload_to=get_event_photo_path, null=True, blank=True)
	image5 = models.ImageField(upload_to=get_event_photo_path, null=True, blank=True)
	image6 = models.ImageField(upload_to=get_event_photo_path, null=True, blank=True)

	def __str__(self):
		return str(self.event.name) + "Catalogue"

Event/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import EventCategory, Event, Team, Member
from UserAuth.models import User
# Create your views here.

def event(request):
	event_template = 'Event/events.html'
	event_cat = EventCategory.objects.all().order_by("web_priority")
	all_events = list()
	for _ in event_cat:
		events = Event.objects.filter(event_category__id=_.id).order_by("web_priority")
		all_events.append({"category":_, "events":events})
	part = list()
	teams = list()
	try:
		participated_events = Team.objects.filter(leader__username=request.user.username)
		part = list()
		for obj in participated_events:
			part.append(obj.event)
			teams.append(obj)

		participated_events = Member.objects.filter(email=request.user.email)
		for obj in participated_events:
			part.append(obj.team.event)
			teams.append(obj.team)
	except Exception as e:
		pass	
	# print(part)
	return render(request, event_template, {"event_category":event_cat, "all_events":all_events, "participated_events":part, "teams":teams})

@login_required(login_url=settings.LOGIN_REDIRECT_URL)
def eventRegistration(request):
	if request.method=='GET':
		event_id = request.GET.get('event_id')
		try:
			event = Event.objects.get(id=event_id)
		except Exception as e:
			print(e)
			return HttpResponseRedirect(reverse('Event:events'))

		if request.user.is_authenticated and not event.registration_closed:
			check = Team.objects.filter(leader__username=request.user.username, event__id=event_id)
			if len(check)==0 and len(Team.objects.filter(event__id=event.id)) < event.participant_limit:
				team = Team()
				team.team_name = request.user.username
				team.event = event
				team.leader = request.user
				team.save()
			else:
				for _ in check:
					_.delete()

			return HttpResponseRedirect(reverse('Event:events'))
		return HttpResponseRedirect(reverse('UserAuth:user_login'))

@login_required(login_url=settings.LOGIN_REDIRECT_URL)
def teamEventRegistration(request):
	if request.method == 'GET':
		return HttpResponseRedirect(reverse('Event:events'))

	if request.method == 'POST':
		team_name = request.POST.get('team_name')
		event_id = request.POST.get('event_id')
		names = request.POST.getlist('name[]')
		emails = request.POST.getlist('email[]')

		try:
			event = Event.objects.get(id=event_id)
		except Exception as e:
			print(e)
			return HttpResponseRedirect(reverse('Event:events'))
		# print(len(Team.objects.filter(event__id=event.id)), event.participant_limit)
		if not event.registration_closed and len(Team.objects.filter(event__id=event.id)) <	 event.participant_limit:
			try:
				if request.user.is_authenticated and team_name and event_id:
					team = Team()
					team.team_name = team_name
					team.event = event
					team.leader = request.user
					team.save()

					for name, email in zip(names, emails):
						if name or email:
							member = Member.objects.create(team=team, name=name, email=email)
							member.save()
			except Exception as e:
				print(e)
				return HttpResponseRedirect(reverse('Event:events'))
		return HttpResponseRedirect(reverse('Event:events'))
	pass

@login_required(login_url=settings.LOGIN_REDIRECT_URL)
def eventTeamEdit(request):
	if request.method == 'POST':
		leader_email = request.POST.get('leader_email')
		event_id = request.POST.get('event_id')
		team_name = request.POST.get('team_name')
		names = request.POST.getlist('name[]')
		emails = request.POST.getlist('email[]')

		try:
			team = Team.objects.get(event__id=event_id, leader__email=leader_email)
			team.delete()

			team = Team()
			team.team_name = team_name
			team.event = Event.objects.get(id=event_id)
			team.leader = User.objects.get(email=leader_email)
			team.save()

			for name, email in zip(names, emails):
				if name or email:
					member = Member.objects.create(team=team, name=name, email=email)
					member.save()
		except Exception as e:
			print(e)
		return HttpResponseRedirect(reverse('Event:events'))

Event/templates/Event/events.html
{% extends 'UserAuth/index.html' %}
{% load staticfiles %}

{% block page-title %}
	<title>Events | Abhisarga 2k19</title>
{% endblock %}

{% block link %}
	<link rel="stylesheet" type="text/css" href="{% static 'assets/css/events.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/common.css' %}">
	<script src="{% static 'assets/js/menu.js' %}"></script>
    <script src="{% static 'assets/js/events.js' %}"></script>
{% endblock %}
{% block content %}
<div id="bar">
	<a href="{% url 'UserAuth:home' %}"><img src="{% static 'assets/img/default-logo.png' %}" alt="Abhisarga 2K19" id="bar-logo"></a>
	<div id="menu" onclick="menuopen()">
		<div></div>
		<div></div>
		<div></div>
	</div>
	{% if request.user.is_authenticated %}
	<div id="login">
		<!-- <img src="{% static 'assets/img/svg/circdsg1.svg' %}" width="80%" height="20%" alt=""> -->
		<a href="{% url 'UserAuth:logout' %}">Log Out</a>
		<!-- <img src="{% static 'assets/img/svg/circdsg2.svg' %}" width="80%" height="20%" alt=""> -->
	</div>
	<div id="register">
		<!-- <img src="{% static 'assets/img/svg/circdsg1.svg' %}" width="80%" height="20%" alt=""> -->
		<a href="{% url 'UserAuth:profile' %}">Profile</a>
		<!-- <img src="{% static 'assets/img/svg/circdsg2.svg' %}" width="80%" height="20%" alt=""> -->
	</div>
	{% else %}
	<div id="register">
		<!-- <img src="{% static 'assets/img/svg/circdsg1.svg' %}" width="80%" height="20%" alt=""> -->
		<a href="{% url 'UserAuth:user_registration' %}">REGISTER</a>
		<!-- <img src="{% static 'assets/img/svg/circdsg2.svg' %}" width="80%" height="20%" alt=""> -->
	</div>
	<div id="login">
		<!-- <img src="{% static 'assets/img/svg/circdsg1.svg' %}" width="80%" height="20%" alt=""> -->
		<a href="{% url 'UserAuth:user_login' %}">LOGIN</a>
		<!-- <img src="{% static 'assets/img/svg/circdsg2.svg' %}" width="80%" height="20%" alt=""> -->
	</div>
	{% endif %}
</div>
<div id="select-list">
	<select id="eventselect" onchange="changecontent()">
		{% for category in event_category %}
		<option value="{{forloop.counter0}}">{{category.category}}</option>
		{% endfor %}
	</select>
	<img src="{% static 'assets/img/arrow.png' %}" alt="">
</div>
<div id="event-content">
	{% for object in all_events %}
	{% if forloop.counter0 == 0 %} <div class="events-internal"> {% else %} <div class="events-internal" style="display: none;"> {% endif %}
		{% for event in object.events %}
		<div class="single-event">
			<h1>{{ event.name }}</h1>
			<div class="image">
				{% if event.logo %}
				<img src="{{ event.logo.url }}" alt="{{ event.name }}">
				{% endif %}
				<div></div>
			</div>
			<div class="event-details">
				<p class="scrollbar">
					{{ event.description|linebreaksbr }}
				</p>
				<div class="s-info">
					<img src="{% static 'assets/img/svg/design.svg' %}" alt="">
					<span><img src="{% static 'assets/img/svg/calender.svg' %}" alt="">{{ event.event_from|date:"M d, Y" }}</span>
					<span><img src="{% static 'assets/img/svg/rupee.svg' %}" alt="">{{ event.prize }}</span>
				</div>

				{% if event.registration_closed %}
				<div class="b-link">
					<a href="javascript:function() { return false; }">Closed</a>
				</div>
				{% elif event.registration_full %}
				<div class="b-link">
					<a href="javascript:function() { return false; }">We're Full</a>
				</div>
				{% elif event in participated_events %}
				<div class="b-link">
					<a onclick="return confirm('Are you sure you want to deregister from this event?')" href="{% url 'Event:eventRegistration' %}?event_id={{event.id}}">Registered</a>
				</div>
				{% else %}{% if event.team_event and request.user.is_authenticated %}
				<div class="b-link event-register">
					Register
				</div>
				{% elif event.team_event and not request.user.is_authenticated %}
				<div class="b-link">
					<a href="{% url 'Event:teamEventRegistration' %}">Register</a>
				</div>
				{% else %}
				<div class="b-link">
					<a href="{% url 'Event:eventRegistration' %}?event_id={{event.id}}">Register</a>
				</div>
				{% endif %}{% endif %}
				{% if event in participated_events and event.team_event %}
				<div class="b-link event-team">
					Team
				</div>
				{% endif %}
				<div class="b-link event-rules">
					Rules
				</div>
			</div>
			<div class="modal modal-rules" style="display: none;">
				<div class="modal-container scrollbar">
					<div class="modal-close">
					</div>
					<h1>Rules and Regulations</h1>
					<div class="modal-content">
						<ul>
							{{ event.rules|safe }}
						</ul>
					</div>
				</div>
			</div>
			{% if event.team_event and not event in participated_events %}
			<div class="modal modal-register" style="display: none;">
				<div class="modal-container scrollbar">
					<div class="modal-close">
					</div>
					<h1>{{ event.name }} Registration</h1>
					<div class="modal-content">
						<div class="register-rules">
						</div>
						<div class="register-form">
							<form action="{% url 'Event:teamEventRegistration' %}" method="post">
								{% csrf_token %}
								<input type="hidden" name="event_id" value="{{ event.id }}">
								<div>
									<div class="one-field">
							            <label for="name"><img src="{% static 'assets/img/svg/name.svg' %}" alt=""></label><input type="text" placeholder="Team Name" name="team_name" required="">
							        </div>
								</div>
								<br>
								<div>
									<div class="one-field">
							            <label for="name"><img src="{% static 'assets/img/svg/name.svg' %}" alt=""></label><input type="text" placeholder="Name" value="{{ request.user.username }}" readonly="">
							        </div>
							        <div class="one-field">
							        	<label for="email"><img src="{% static 'assets/img/svg/email.svg' %}" alt=""></label><input type="email" placeholder="E-mail" value="{{ request.user.email }}" readonly="">
							        </div>
								</div>
								{% with ''|center:event.participant_count as range %}
								{% for _ in range %}
								{% if forloop.counter0 != 0 %}
								<div>
									<div class="one-field">
							            <label for="name"><img src="{% static 'assets/img/svg/name.svg' %}" alt=""></label><input type="text" placeholder="Name(Optional)" name="name[]">
							        </div>
							        <div class="one-field">
							        	<label for="email"><img src="{% static 'assets/img/svg/email.svg' %}" alt=""></label><input type="email" placeholder="E-mail(Optional)" name="email[]">
							        </div>
								</div>
								{% endif %}
								{% endfor %}
								{% endwith %}
			          			<!-- <div>
									<input type="checkbox" name="agree" style="display:none" class="register-agree"><span><span class="register-checkbox">&#10004;</span>I agree to the terms and condition.</span>
			          			</div> -->
								<div>
			            			<button type="submit">Register Me</button>
			          			</div>
			        		</form>
						</div>
					</div>
				</div>
			</div>
			{% elif event in participated_events %}
			{% for team in teams %}
			{% if team.event.id == event.id %}
			<div class="modal modal-team" style="display: none;">
				<div class="modal-container scrollbar">
					<div class="modal-close">
					</div>
					<h1>{{ event.name }} Registration</h1>
					<div class="modal-content">
						<div class="register-rules">
						</div>
						<div class="register-form">
							<form action="{% url 'Event:eventTeamEdit' %}" method="post">
								{% csrf_token %}
								<input type="hidden" name="event_id" value="{{ event.id }}">
								<div>
									<div class="one-field">
							            <label for="name"><img src="{% static 'assets/img/svg/name.svg' %}" alt=""></label><input type="text" placeholder="Team Name" name="team_name" required="" value="{{team.team_name}}">
							        </div>
								</div>
								<br>
								<div>
									<div class="one-field">
							            <label for="name"><img src="{% static 'assets/img/svg/name.svg' %}" alt=""></label><input type="text" placeholder="Name" value="{{team.leader.username}}" readonly="" name="leader_name">
							        </div>
							        <div class="one-field">
							        	<label for="email"><img src="{% static 'assets/img/svg/email.svg' %}" alt=""></label><input type="email" placeholder="E-mail" value="{{ team.leader.email }}" readonly="" name="leader_email">
							        </div>
								</div>
								{% for member in team.belong_to_team.all %}
								<div>
									<div class="one-field">
							            <label for="name"><img src="{% static 'assets/img/svg/name.svg' %}" alt=""></label><input type="text" placeholder="Name(Optional)" name="name[]" value="{{ member.name }}">
							        </div>
							        <div class="one-field">
							        	<label for="email"><img src="{% static 'assets/img/svg/email.svg' %}" alt=""></label><input type="email" placeholder="E-mail(Optional)" name="email[]" value="{{ member.email }}">
							        </div>
								</div>
								{% endfor %}
								{% with ''|center:event.participant_count as range %}
								{% for _ in range %}
								{% if forloop.counter0 > team.belong_to_team.all|length %}
								<div>
									<div class="one-field">
							            <label for="name"><img src="{% static 'assets/img/svg/name.svg' %}" alt=""></label><input type="text" placeholder="Name(Optional)" name="name[]">
							        </div>
							        <div class="one-field">
							        	<label for="email"><img src="{% static 'assets/img/svg/email.svg' %}" alt=""></label><input type="email" placeholder="E-mail(Optional)" name="email[]">
							        </div>
								</div>
								{% endif %}
								{% endfor %}
								{% endwith %}
			          			<!-- <div>
									<input type="checkbox" name="agree" style="display:none" class="register-agree"><span><span class="register-checkbox">&#10004;</span>I agree to the terms and condition.</span>
			          			</div> -->
								<div>
			            			<button type="submit">Submit</button>
			          			</div>
			        		</form>
						</div>
					</div>
				</div>
			</div>
			{% endif %}
			{% endfor %}
			{% endif %}
		</div>
		{% endfor %}
	</div>
	{% endfor %}
</div>

<div id="listnav">
  <ul>
  	{% for category in event_category %}{% if forloop.counter0 == 0 %}
    <li class="nav-link active-link" value="{{forloop.counter0}}" onclick="changeselect(this)">{{ category.category }}<hr></li>
    {% else %}
    <li class="nav-link" value="{{forloop.counter0}}" onclick="changeselect(this)">{{ category.category }}<hr></li>
    {% endif %}{% endfor %}
  </ul>
</div>
{% endblock %}